Resources:
  CdkExamQueue4A5FE4BD:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 300
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: CdkExamStack/CdkExamQueue/Resource
  CdkExamQueuePolicyFD5DD006:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
          - Action: sqs:SendMessage
            Condition:
              ArnEquals:
                aws:SourceArn:
                  Ref: CdkExamTopic2E1C3675
            Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Resource:
              Fn::GetAtt:
                - CdkExamQueue4A5FE4BD
                - Arn
        Version: "2012-10-17"
      Queues:
        - Ref: CdkExamQueue4A5FE4BD
    Metadata:
      aws:cdk:path: CdkExamStack/CdkExamQueue/Policy/Resource
  CdkExamQueueCdkExamStackCdkExamTopic4BA6EBB838A514C0:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint:
        Fn::GetAtt:
          - CdkExamQueue4A5FE4BD
          - Arn
      Protocol: sqs
      TopicArn:
        Ref: CdkExamTopic2E1C3675
    DependsOn:
      - CdkExamQueuePolicyFD5DD006
    Metadata:
      aws:cdk:path: CdkExamStack/CdkExamQueue/CdkExamStackCdkExamTopic4BA6EBB8/Resource
  MyVPCAFB07A31:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.30.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: CdkExamStack/MyVPC
    Metadata:
      aws:cdk:path: CdkExamStack/MyVPC/Resource
  MyVPCPublicSubnetSubnet1SubnetADEB7CE8:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      CidrBlock: 10.30.0.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: aws-cdk:subnet-name
          Value: PublicSubnet
        - Key: aws-cdk:subnet-type
          Value: Public
        - Key: Name
          Value: CdkExamStack/MyVPC/PublicSubnetSubnet1
      VpcId:
        Ref: MyVPCAFB07A31
    Metadata:
      aws:cdk:path: CdkExamStack/MyVPC/PublicSubnetSubnet1/Subnet
  MyVPCPublicSubnetSubnet1RouteTableA18590BC:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: CdkExamStack/MyVPC/PublicSubnetSubnet1
      VpcId:
        Ref: MyVPCAFB07A31
    Metadata:
      aws:cdk:path: CdkExamStack/MyVPC/PublicSubnetSubnet1/RouteTable
  MyVPCPublicSubnetSubnet1RouteTableAssociationD2429CDD:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: MyVPCPublicSubnetSubnet1RouteTableA18590BC
      SubnetId:
        Ref: MyVPCPublicSubnetSubnet1SubnetADEB7CE8
    Metadata:
      aws:cdk:path: CdkExamStack/MyVPC/PublicSubnetSubnet1/RouteTableAssociation
  MyVPCPublicSubnetSubnet1DefaultRouteB6449071:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: MyVPCIGW30AB6DD6
      RouteTableId:
        Ref: MyVPCPublicSubnetSubnet1RouteTableA18590BC
    DependsOn:
      - MyVPCVPCGWE6F260E1
    Metadata:
      aws:cdk:path: CdkExamStack/MyVPC/PublicSubnetSubnet1/DefaultRoute
  MyVPCPublicSubnetSubnet2Subnet5D9E58E5:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: ""
      CidrBlock: 10.30.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: aws-cdk:subnet-name
          Value: PublicSubnet
        - Key: aws-cdk:subnet-type
          Value: Public
        - Key: Name
          Value: CdkExamStack/MyVPC/PublicSubnetSubnet2
      VpcId:
        Ref: MyVPCAFB07A31
    Metadata:
      aws:cdk:path: CdkExamStack/MyVPC/PublicSubnetSubnet2/Subnet
  MyVPCPublicSubnetSubnet2RouteTable217CF8CD:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: CdkExamStack/MyVPC/PublicSubnetSubnet2
      VpcId:
        Ref: MyVPCAFB07A31
    Metadata:
      aws:cdk:path: CdkExamStack/MyVPC/PublicSubnetSubnet2/RouteTable
  MyVPCPublicSubnetSubnet2RouteTableAssociationD5472F1C:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: MyVPCPublicSubnetSubnet2RouteTable217CF8CD
      SubnetId:
        Ref: MyVPCPublicSubnetSubnet2Subnet5D9E58E5
    Metadata:
      aws:cdk:path: CdkExamStack/MyVPC/PublicSubnetSubnet2/RouteTableAssociation
  MyVPCPublicSubnetSubnet2DefaultRoute5FA31DE0:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: MyVPCIGW30AB6DD6
      RouteTableId:
        Ref: MyVPCPublicSubnetSubnet2RouteTable217CF8CD
    DependsOn:
      - MyVPCVPCGWE6F260E1
    Metadata:
      aws:cdk:path: CdkExamStack/MyVPC/PublicSubnetSubnet2/DefaultRoute
  MyVPCIGW30AB6DD6:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: CdkExamStack/MyVPC
    Metadata:
      aws:cdk:path: CdkExamStack/MyVPC/IGW
  MyVPCVPCGWE6F260E1:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId:
        Ref: MyVPCIGW30AB6DD6
      VpcId:
        Ref: MyVPCAFB07A31
    Metadata:
      aws:cdk:path: CdkExamStack/MyVPC/VPCGW
  MyVPCRestrictDefaultSecurityGroupCustomResourceC3FF5EE0:
    Type: Custom::VpcRestrictDefaultSG
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - CustomVpcRestrictDefaultSGCustomResourceProviderHandlerDC833E5E
          - Arn
      DefaultSecurityGroupId:
        Fn::GetAtt:
          - MyVPCAFB07A31
          - DefaultSecurityGroup
      Account:
        Ref: AWS::AccountId
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: CdkExamStack/MyVPC/RestrictDefaultSecurityGroupCustomResource/Default
  CustomVpcRestrictDefaultSGCustomResourceProviderRole26592FE0:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
      ManagedPolicyArns:
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: Inline
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:AuthorizeSecurityGroupIngress
                  - ec2:AuthorizeSecurityGroupEgress
                  - ec2:RevokeSecurityGroupIngress
                  - ec2:RevokeSecurityGroupEgress
                Resource:
                  - Fn::Join:
                      - ""
                      - - "arn:"
                        - Ref: AWS::Partition
                        - ":ec2:"
                        - Ref: AWS::Region
                        - ":"
                        - Ref: AWS::AccountId
                        - :security-group/
                        - Fn::GetAtt:
                            - MyVPCAFB07A31
                            - DefaultSecurityGroup
    Metadata:
      aws:cdk:path: CdkExamStack/Custom::VpcRestrictDefaultSGCustomResourceProvider/Role
  CustomVpcRestrictDefaultSGCustomResourceProviderHandlerDC833E5E:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: ee7de53d64cc9d6248fa6aa550f92358f6c907b5efd6f3298aeab1b5e7ea358a.zip
      Timeout: 900
      MemorySize: 128
      Handler: __entrypoint__.handler
      Role:
        Fn::GetAtt:
          - CustomVpcRestrictDefaultSGCustomResourceProviderRole26592FE0
          - Arn
      Runtime: nodejs18.x
      Description: Lambda function for removing all inbound/outbound rules from the VPC default security group
    DependsOn:
      - CustomVpcRestrictDefaultSGCustomResourceProviderRole26592FE0
    Metadata:
      aws:cdk:path: CdkExamStack/Custom::VpcRestrictDefaultSGCustomResourceProvider/Handler
      aws:asset:path: asset.ee7de53d64cc9d6248fa6aa550f92358f6c907b5efd6f3298aeab1b5e7ea358a
      aws:asset:property: Code
  MyEC2InstanceInstanceSecurityGroup06C6622F:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: CdkExamStack/MyEC2Instance/InstanceSecurityGroup
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      Tags:
        - Key: Name
          Value: CdkExamStack/MyEC2Instance
      VpcId:
        Ref: MyVPCAFB07A31
    Metadata:
      aws:cdk:path: CdkExamStack/MyEC2Instance/InstanceSecurityGroup/Resource
  MyEC2InstanceInstanceRole1A6C2310:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
        Version: "2012-10-17"
      Tags:
        - Key: Name
          Value: CdkExamStack/MyEC2Instance
    Metadata:
      aws:cdk:path: CdkExamStack/MyEC2Instance/InstanceRole/Resource
  MyEC2InstanceInstanceProfile9377ECBE:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: MyEC2InstanceInstanceRole1A6C2310
    Metadata:
      aws:cdk:path: CdkExamStack/MyEC2Instance/InstanceProfile
  MyEC2InstanceB097982C:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      IamInstanceProfile:
        Ref: MyEC2InstanceInstanceProfile9377ECBE
      ImageId:
        Ref: SsmParameterValueawsserviceamiamazonlinuxlatestamzn2amihvmx8664gp2C96584B6F00A464EAD1953AFF4B05118Parameter
      InstanceType: t2.micro
      SecurityGroupIds:
        - Fn::GetAtt:
            - MyEC2InstanceInstanceSecurityGroup06C6622F
            - GroupId
      SubnetId:
        Ref: MyVPCPublicSubnetSubnet1SubnetADEB7CE8
      Tags:
        - Key: Name
          Value: CdkExamStack/MyEC2Instance
      UserData:
        Fn::Base64: "#!/bin/bash"
    DependsOn:
      - MyEC2InstanceInstanceRole1A6C2310
    Metadata:
      aws:cdk:path: CdkExamStack/MyEC2Instance/Resource
  CdkExamTopic2E1C3675:
    Type: AWS::SNS::Topic
    Metadata:
      aws:cdk:path: CdkExamStack/CdkExamTopic/Resource
  MySecret8FE80B51:
    Type: AWS::SecretsManager::Secret
    Properties:
      GenerateSecretString:
        ExcludePunctuation: true
        GenerateStringKey: password
        PasswordLength: 12
        SecretStringTemplate: '{"username":"admin"}'
      Name: metrodb-secrets
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: CdkExamStack/MySecret/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/21RTW/CMAz9LbuHTGWHbUfWA+LWFcR1SlPDDG3SxQ4IVf3vc7+GNu0Sv/f8bMfJUidPrzp5MFda2PK8qLDQ7ZaNPSuRPlr6It2+R4ig0oMbwXBmvkJ7+xFH2ily4t/GgmzAhtG73vGL73yDtlcH0CmwS93um0HaZ6nKYiGtpMQBT8UTyn1k2Jmigrt+11ZE3qKZZw6JHmwcQxDn2jBczW0aM7EVy6qfNThWG0dsnAW1BRsD8m0dfGyGSX+F2dopNLVucz/eaI5zOgv+gJW4CGwApto4c4Qg7zPwqbWgrlM5kI9BpqeR2Nd3Km3/T0n3C5YQ3gyBkuWB5duO6I59TWaCqUEW70nqXYn9u3TK+RL0iR4vyYtOnuXfT4S4CNEx1qDzMX4DJLFdSRQCAAA=
    Metadata:
      aws:cdk:path: CdkExamStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Parameters:
  SsmParameterValueawsserviceamiamazonlinuxlatestamzn2amihvmx8664gp2C96584B6F00A464EAD1953AFF4B05118Parameter:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - il-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - me-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

